{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1 행정동 파악\n",
    "#### 1.1 Read Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>FTR_CDE</th>\n",
       "      <th>HJD_CDE</th>\n",
       "      <th>HJD_NAM</th>\n",
       "      <th>SHAPE_AREA</th>\n",
       "      <th>SHAPE_LEN</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>UC300</td>\n",
       "      <td>41590587</td>\n",
       "      <td>동탄3동</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>UC300</td>\n",
       "      <td>41590540</td>\n",
       "      <td>병점2동</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>UC300</td>\n",
       "      <td>41590585</td>\n",
       "      <td>동탄1동</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>UC300</td>\n",
       "      <td>41590550</td>\n",
       "      <td>반월동</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>UC300</td>\n",
       "      <td>41590586</td>\n",
       "      <td>동탄2동</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  FTR_CDE   HJD_CDE HJD_NAM  SHAPE_AREA  SHAPE_LEN\n",
       "0   UC300  41590587    동탄3동         0.0        0.0\n",
       "1   UC300  41590540    병점2동         0.0        0.0\n",
       "2   UC300  41590585    동탄1동         0.0        0.0\n",
       "3   UC300  41590550     반월동         0.0        0.0\n",
       "4   UC300  41590586    동탄2동         0.0        0.0"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = pd.read_csv('C:/Users/User/Desktop/공공빅데이터/화성시/Project1 폐기물/GIS/화성시_행정동.csv',encoding='ANSI')\n",
    "df = pd.DataFrame(data)\n",
    "df.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>구분</th>\n",
       "      <th>업체명</th>\n",
       "      <th>담당구역(행정동)</th>\n",
       "      <th>담당구역(법정동)</th>\n",
       "      <th>사무실 전화번호</th>\n",
       "      <th>주소지</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1구역</td>\n",
       "      <td>㈜은호ENT</td>\n",
       "      <td>동탄2동, 동탄3동</td>\n",
       "      <td>반송동(동탄문화센터로 남측일원), \\n능동(화성동탄1택지개발지구 포함)</td>\n",
       "      <td>031-376-9221</td>\n",
       "      <td>정남면 신백길 12-44</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2구역</td>\n",
       "      <td>㈜원천환경</td>\n",
       "      <td>병점2동, 반월동, 진안동</td>\n",
       "      <td>병점중앙로 서측일원, 반월동, 진안동, 능동</td>\n",
       "      <td>031-353-7333\\n031-353-7334</td>\n",
       "      <td>향남읍 만년로 151번길 62</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3구역</td>\n",
       "      <td>㈜평촌</td>\n",
       "      <td>봉담읍, 매송면, 비봉면</td>\n",
       "      <td>봉담읍, 매송면, 비봉면</td>\n",
       "      <td>031-353-6263</td>\n",
       "      <td>향남읍 한두골길 21-53</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4구역</td>\n",
       "      <td>㈜화성</td>\n",
       "      <td>남양읍, 마도면, 송산면, 서신면, 송산그린시티</td>\n",
       "      <td>남양읍, 마도면, 송산면, 서신면, 새솔동</td>\n",
       "      <td>031-227-5157</td>\n",
       "      <td>봉담읍 분천길95번길 88</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5구역</td>\n",
       "      <td>향원실업㈜</td>\n",
       "      <td>향남읍</td>\n",
       "      <td>향남읍</td>\n",
       "      <td>031-351-3223</td>\n",
       "      <td>장안면 3.1만세로 322번길 41</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    구분     업체명                   담당구역(행정동)  \\\n",
       "0  1구역  ㈜은호ENT                  동탄2동, 동탄3동   \n",
       "1  2구역   ㈜원천환경              병점2동, 반월동, 진안동   \n",
       "2  3구역     ㈜평촌               봉담읍, 매송면, 비봉면   \n",
       "3  4구역     ㈜화성  남양읍, 마도면, 송산면, 서신면, 송산그린시티   \n",
       "4  5구역   향원실업㈜                         향남읍   \n",
       "\n",
       "                                 담당구역(법정동)                    사무실 전화번호  \\\n",
       "0  반송동(동탄문화센터로 남측일원), \\n능동(화성동탄1택지개발지구 포함)                031-376-9221   \n",
       "1                 병점중앙로 서측일원, 반월동, 진안동, 능동  031-353-7333\\n031-353-7334   \n",
       "2                            봉담읍, 매송면, 비봉면                031-353-6263   \n",
       "3                  남양읍, 마도면, 송산면, 서신면, 새솔동                031-227-5157   \n",
       "4                                      향남읍                031-351-3223   \n",
       "\n",
       "                   주소지  \n",
       "0        정남면 신백길 12-44  \n",
       "1     향남읍 만년로 151번길 62  \n",
       "2       향남읍 한두골길 21-53  \n",
       "3       봉담읍 분천길95번길 88  \n",
       "4  장안면 3.1만세로 322번길 41  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data02 = pd.read_csv('C:/Users/User/Desktop/공공빅데이터/화성시/Project1 폐기물/분석자료/업체별 처리구역(2001).csv',encoding='utf-8')\n",
    "df02 = pd.DataFrame(data02)\n",
    "df02.head(5)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "&nbsp;\n",
    "#### 1.2 거래처 담당구역과 행정동 일치"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['동탄3동', '병점2동', '동탄1동', '반월동', '동탄2동', '기배동', '정남면', '화산동', '병점1동', '비봉면', '장안면', '봉담읍', '팔탄면', '향남읍', '양감면', '매송면', '우정읍', '진안동', '남양읍', '서신면', '송산면', '마도면', '동탄4동', '동탄5동', '동탄6동', '동탄7동', '새솔동', '동탄8동']\n",
      "['동탄2동, 동탄3동', '병점2동, 반월동, 진안동', '봉담읍, 매송면, 비봉면', '남양읍, 마도면, 송산면, 서신면, 송산그린시티', '향남읍', '우정읍, 장안면, 양감면, 팔탄면', '동탄6동, 동탄7동', '병점1동, 화산동, 기배동, 정남면', '동탄1동', '동탄5동', '동탄4동', '동탄8동']\n"
     ]
    }
   ],
   "source": [
    "gis_list=list(df['HJD_NAM'])\n",
    "drive_list=list(df02['담당구역(행정동)'])\n",
    "\n",
    "print(gis_list)\n",
    "print(drive_list)\n",
    "# 담당구역에서 value가 list로 들어간 경우가 있음"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['동탄2동', '동탄3동', '병점2동', '반월동', '진안동', '봉담읍', '매송면', '비봉면', '남양읍', '마도면', '송산면', '서신면', '송산그린시티', '향남읍', '우정읍', '장안면', '양감면', '팔탄면', '동탄6동', '동탄7동', '병점1동', '화산동', '기배동', '정남면', '동탄1동', '동탄5동', '동탄4동', '동탄8동']\n"
     ]
    }
   ],
   "source": [
    "# 담당구역의 value를 모두 string으로 전환하여 list 재 생성\n",
    "\n",
    "len(df02['담당구역(행정동)'])   # 12\n",
    "\n",
    "drive_list_str = []\n",
    "\n",
    "for i in range(0,12) :\n",
    "    mid = []\n",
    "    mid = df02['담당구역(행정동)'][i].split(',')\n",
    "    \n",
    "    for item in mid :\n",
    "        item=item.strip()\n",
    "        drive_list_str.append(item)\n",
    "        \n",
    "print(drive_list_str)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# list 일치 확인\n",
    "\n",
    "gis_list_cor = []\n",
    "gis_list_nan = []\n",
    "\n",
    "drive_list_cor = []\n",
    "drive_list_nan = []\n",
    "\n",
    "for g in gis_list :\n",
    "    if g in drive_list_str :\n",
    "        gis_list_cor.append(g)\n",
    "    else :\n",
    "        gis_list_nan.append(g)\n",
    "        \n",
    "for d in drive_list_str :\n",
    "    if d in gis_list :\n",
    "        drive_list_cor.append(d)\n",
    "    else :\n",
    "        drive_list_nan.append(d)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "일치하는 행정동 ['동탄3동', '병점2동', '동탄1동', '반월동', '동탄2동', '기배동', '정남면', '화산동', '병점1동', '비봉면', '장안면', '봉담읍', '팔탄면', '향남읍', '양감면', '매송면', '우정읍', '진안동', '남양읍', '서신면', '송산면', '마도면', '동탄4동', '동탄5동', '동탄6동', '동탄7동', '동탄8동']\n",
      "담당이 없는 행정동 ['새솔동']\n",
      "존재하지 않는 처리구역 ['송산그린시티']\n"
     ]
    }
   ],
   "source": [
    "print('일치하는 행정동',gis_list_cor)\n",
    "print('담당이 없는 행정동',gis_list_nan)\n",
    "print('존재하지 않는 처리구역', drive_list_nan)\n",
    "\n",
    "con_list=gis_list_cor.copy()  ## 담당구역 list\n",
    "\n",
    "# 담당이 없는 행정동 ['새솔동'] : 새솔동은 4구역에서 법정동으로 포함됨\n",
    "# 존재하지 않는 처리 구역 ['송산그린시티'] : 송산그린시티가 새솔동 내부로 확인됨\n",
    "## 따라서 '송산그린시티' -> '새솔동'으로 처리하여 매칭"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- 폐기물 처리업체와 행정동 비교결과 대부분 일치  \n",
    "['동탄3동', '병점2동', '동탄1동', '반월동', '동탄2동', '기배동', '정남면', '화산동', '병점1동', '비봉면', '장안면', '봉담읍', '팔탄면', '향남읍', '양감면', '매송면', '우정읍', '진안동', '남양읍', '서신면', '송산면', '마도면', '동탄4동', '동탄5동', '동탄6동', '동탄7동', '동탄8동']   \n",
    "&nbsp;  \n",
    "- 담당이 없는 행정동  \n",
    "'새솔동'은 4구역의 담당 법정동이며, 4구역에서 '송산그린시티'를 담당함 -> '새솔동'은 4구역으로 처리  \n",
    "&nbsp;  \n",
    "- 동부 폐기물 집계파일 확인결과 처리업체 목록에 없는 기업 존재  \n",
    "-> 해당 업체의 담당구역 확인 필요함"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2 거래처 담당구역 파악  \n",
    "### 2.1 Data Setting\n",
    "- 동부적환장"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>1차 계량일</th>\n",
       "      <th>순번</th>\n",
       "      <th>2차계량일</th>\n",
       "      <th>1차시간</th>\n",
       "      <th>2차시간</th>\n",
       "      <th>차량번호숫자</th>\n",
       "      <th>거래처</th>\n",
       "      <th>품명</th>\n",
       "      <th>소속회사</th>\n",
       "      <th>공차중량</th>\n",
       "      <th>총중량</th>\n",
       "      <th>실중량</th>\n",
       "      <th>입/출고</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>1</td>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>9:23</td>\n",
       "      <td>9:25</td>\n",
       "      <td>8544</td>\n",
       "      <td>병점2동</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>화성시청</td>\n",
       "      <td>2210</td>\n",
       "      <td>2190</td>\n",
       "      <td>20</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>2</td>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>9:53</td>\n",
       "      <td>10:01</td>\n",
       "      <td>1119</td>\n",
       "      <td>(주)부경크린</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>반입업체</td>\n",
       "      <td>2390</td>\n",
       "      <td>2020</td>\n",
       "      <td>370</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>3</td>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>9:53</td>\n",
       "      <td>10:01</td>\n",
       "      <td>898</td>\n",
       "      <td>(주)은호ENT</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>반입업체</td>\n",
       "      <td>2720</td>\n",
       "      <td>2300</td>\n",
       "      <td>420</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>4</td>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>10:05</td>\n",
       "      <td>10:11</td>\n",
       "      <td>779</td>\n",
       "      <td>(주)크린시티화성</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>반입업체</td>\n",
       "      <td>2590</td>\n",
       "      <td>2280</td>\n",
       "      <td>310</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>5</td>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>10:07</td>\n",
       "      <td>10:13</td>\n",
       "      <td>108</td>\n",
       "      <td>(주)부경크린</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>반입업체</td>\n",
       "      <td>2650</td>\n",
       "      <td>2170</td>\n",
       "      <td>480</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       1차 계량일  순번       2차계량일   1차시간   2차시간 차량번호숫자        거래처   품명  소속회사  \\\n",
       "0  2019-01-02   1  2019-01-02   9:23   9:25   8544       병점2동  폐합성  화성시청   \n",
       "1  2019-01-02   2  2019-01-02   9:53  10:01   1119    (주)부경크린  폐합성  반입업체   \n",
       "2  2019-01-02   3  2019-01-02   9:53  10:01    898   (주)은호ENT  폐합성  반입업체   \n",
       "3  2019-01-02   4  2019-01-02  10:05  10:11    779  (주)크린시티화성  폐합성  반입업체   \n",
       "4  2019-01-02   5  2019-01-02  10:07  10:13    108    (주)부경크린  폐합성  반입업체   \n",
       "\n",
       "   공차중량   총중량  실중량 입/출고  \n",
       "0  2210  2190   20   입고  \n",
       "1  2390  2020  370   입고  \n",
       "2  2720  2300  420   입고  \n",
       "3  2590  2280  310   입고  \n",
       "4  2650  2170  480   입고  "
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 동부적환장_계근량(19) Read\n",
    "\n",
    "data03=pd.read_csv('C:/Users/User/Desktop/공공빅데이터/화성시/Project1 폐기물/분석자료/동부적환장_계근량(19)(반입).csv',\n",
    "                   encoding='utf-8')\n",
    "df03=pd.DataFrame(data03)\n",
    "df03.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>1차 계량일</th>\n",
       "      <th>순번</th>\n",
       "      <th>2차계량일</th>\n",
       "      <th>1차시간</th>\n",
       "      <th>2차시간</th>\n",
       "      <th>차량번호숫자</th>\n",
       "      <th>거래처</th>\n",
       "      <th>품명</th>\n",
       "      <th>소속회사</th>\n",
       "      <th>공차중량</th>\n",
       "      <th>총중량</th>\n",
       "      <th>실중량</th>\n",
       "      <th>입/출고</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2020-01-01</td>\n",
       "      <td>3</td>\n",
       "      <td>2020-01-01</td>\n",
       "      <td>15:38</td>\n",
       "      <td>15:38</td>\n",
       "      <td>279</td>\n",
       "      <td>동탄출장소</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>(주)화성시청</td>\n",
       "      <td>7,000</td>\n",
       "      <td>8,590</td>\n",
       "      <td>1,590</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>1</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>9:57</td>\n",
       "      <td>10:22</td>\n",
       "      <td>9184</td>\n",
       "      <td>반월동</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>(주)화성시청</td>\n",
       "      <td>2,480</td>\n",
       "      <td>2,180</td>\n",
       "      <td>300</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>2</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>10:04</td>\n",
       "      <td>10:06</td>\n",
       "      <td>8544</td>\n",
       "      <td>병점2동</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>(주)화성시청</td>\n",
       "      <td>2,210</td>\n",
       "      <td>2,190</td>\n",
       "      <td>20</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>4</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>10:10</td>\n",
       "      <td>10:15</td>\n",
       "      <td>9144</td>\n",
       "      <td>정남면</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>(주)화성시청</td>\n",
       "      <td>4,730</td>\n",
       "      <td>4,140</td>\n",
       "      <td>590</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>5</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>10:11</td>\n",
       "      <td>10:15</td>\n",
       "      <td>7934</td>\n",
       "      <td>기배동</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>(주)화성시청</td>\n",
       "      <td>2,520</td>\n",
       "      <td>2,160</td>\n",
       "      <td>360</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       1차 계량일  순번       2차계량일   1차시간   2차시간  차량번호숫자    거래처   품명     소속회사  \\\n",
       "2  2020-01-01   3  2020-01-01  15:38  15:38     279  동탄출장소  폐합성  (주)화성시청   \n",
       "3  2020-01-02   1  2020-01-02   9:57  10:22    9184    반월동  폐합성  (주)화성시청   \n",
       "4  2020-01-02   2  2020-01-02  10:04  10:06    8544   병점2동  폐합성  (주)화성시청   \n",
       "6  2020-01-02   4  2020-01-02  10:10  10:15    9144    정남면  폐합성  (주)화성시청   \n",
       "7  2020-01-02   5  2020-01-02  10:11  10:15    7934    기배동  폐합성  (주)화성시청   \n",
       "\n",
       "   공차중량    총중량    실중량  입/출고  \n",
       "2  7,000  8,590  1,590   입고  \n",
       "3  2,480  2,180    300   입고  \n",
       "4  2,210  2,190     20   입고  \n",
       "6  4,730  4,140    590   입고  \n",
       "7  2,520  2,160    360   입고  "
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 동부적환장_계근량(20) Read\n",
    "\n",
    "data05=pd.read_csv('C:/Users/User/Desktop/공공빅데이터/화성시/Project1 폐기물/분석자료/동부적환장_계근량(20).csv',encoding='utf-8')\n",
    "df05=pd.DataFrame(data05)\n",
    "\n",
    "## print(df05['입/출고'].isnull().sum()) == 0\n",
    "##print(len(df05)) == 5862\n",
    "\n",
    "df05=df05[df05['입/출고']=='입고']\n",
    "df05.to_csv('C:/Users/User/Desktop/공공빅데이터/화성시/Project1 폐기물/분석자료/동부적확장_계근량(20)(입고).csv', encoding='utf-8')\n",
    "df05.head(5)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "&nbsp;  \n",
    "- 서부자원화시설"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>계량일자</th>\n",
       "      <th>계량일시</th>\n",
       "      <th>등록일자</th>\n",
       "      <th>등록일시</th>\n",
       "      <th>순번</th>\n",
       "      <th>이력일자</th>\n",
       "      <th>이력시간</th>\n",
       "      <th>구분</th>\n",
       "      <th>입출</th>\n",
       "      <th>차량번호</th>\n",
       "      <th>...</th>\n",
       "      <th>Inout Flag</th>\n",
       "      <th>In Weight</th>\n",
       "      <th>End Flag</th>\n",
       "      <th>Prod Cost</th>\n",
       "      <th>Imagef No</th>\n",
       "      <th>Imager No</th>\n",
       "      <th>Imagef2 No</th>\n",
       "      <th>Imager2 No</th>\n",
       "      <th>Imageu No</th>\n",
       "      <th>Imageu2 No</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:24:36</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:24:36</td>\n",
       "      <td>1.0</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:24:42</td>\n",
       "      <td>등록</td>\n",
       "      <td>입고</td>\n",
       "      <td>3228</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>1480</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:42:15</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:28:25</td>\n",
       "      <td>4.0</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:42:15</td>\n",
       "      <td>등록</td>\n",
       "      <td>입고</td>\n",
       "      <td>416</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>180</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:50:02</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:30:38</td>\n",
       "      <td>5.0</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:50:02</td>\n",
       "      <td>등록</td>\n",
       "      <td>입고</td>\n",
       "      <td>2460</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>170</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:52:58</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:38:17</td>\n",
       "      <td>7.0</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:52:58</td>\n",
       "      <td>등록</td>\n",
       "      <td>입고</td>\n",
       "      <td>6371</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>220</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>8:02:36</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:55:46</td>\n",
       "      <td>8.0</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>8:02:36</td>\n",
       "      <td>등록</td>\n",
       "      <td>입고</td>\n",
       "      <td>9011</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>1190</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 33 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         계량일자     계량일시        등록일자     등록일시   순번        이력일자     이력시간  구분  입출  \\\n",
       "1  2019-01-01  7:24:36  2019-01-01  7:24:36  1.0  2019-01-01  7:24:42  등록  입고   \n",
       "4  2019-01-01  7:42:15  2019-01-01  7:28:25  4.0  2019-01-01  7:42:15  등록  입고   \n",
       "5  2019-01-01  7:50:02  2019-01-01  7:30:38  5.0  2019-01-01  7:50:02  등록  입고   \n",
       "8  2019-01-01  7:52:58  2019-01-01  7:38:17  7.0  2019-01-01  7:52:58  등록  입고   \n",
       "9  2019-01-01  8:02:36  2019-01-01  7:55:46  8.0  2019-01-01  8:02:36  등록  입고   \n",
       "\n",
       "   차량번호  ... Inout Flag In Weight End Flag Prod Cost     Imagef No  \\\n",
       "1  3228  ...          2      1480        N         0  2.019010e+19   \n",
       "4   416  ...          2       180        N         0  2.019010e+19   \n",
       "5  2460  ...          2       170        N         0  2.019010e+19   \n",
       "8  6371  ...          2       220        N         0  2.019010e+19   \n",
       "9  9011  ...          2      1190        N         0  2.019010e+19   \n",
       "\n",
       "      Imager No    Imagef2 No    Imager2 No     Imageu No    Imageu2 No  \n",
       "1  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  \n",
       "4  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  \n",
       "5  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  \n",
       "8  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  \n",
       "9  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  \n",
       "\n",
       "[5 rows x 33 columns]"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 서부자원화시설_계근량(19) Read - Raw data\n",
    "\n",
    "data07=pd.read_csv('C:/Users/User/Desktop/공공빅데이터/화성시/Project1 폐기물/분석자료/서부자원화시설_계근량(19)(수정용).csv',\n",
    "                   encoding='utf-8')\n",
    "df07=pd.DataFrame(data07)\n",
    "\n",
    "## print(df07['입출'].isnull().sum()) == 1755\n",
    "## print(len(df07)) == 53944\n",
    "\n",
    "df07=df07[df07['입출']=='입고']\n",
    "df07.to_csv('C:/Users/User/Desktop/공공빅데이터/화성시/Project1 폐기물/분석자료/서부자원화시설_계근량(19)(입고).csv', encoding='utf-8')\n",
    "df07.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>전번</th>\n",
       "      <th>계량일자</th>\n",
       "      <th>계량시간</th>\n",
       "      <th>등록일자</th>\n",
       "      <th>등록시간</th>\n",
       "      <th>차량번호</th>\n",
       "      <th>거래처명</th>\n",
       "      <th>품목</th>\n",
       "      <th>구분</th>\n",
       "      <th>공차시간</th>\n",
       "      <th>상차시간</th>\n",
       "      <th>공중량</th>\n",
       "      <th>상중량</th>\n",
       "      <th>실중량</th>\n",
       "      <th>카드번호</th>\n",
       "      <th>1차전면명</th>\n",
       "      <th>1차상면명</th>\n",
       "      <th>지역</th>\n",
       "      <th>작업자</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1.0</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:41</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:32:32</td>\n",
       "      <td>97고6890</td>\n",
       "      <td>(주)평촌</td>\n",
       "      <td>스티로폼</td>\n",
       "      <td>입고</td>\n",
       "      <td>7:41</td>\n",
       "      <td>7:32</td>\n",
       "      <td>5,830</td>\n",
       "      <td>5,920</td>\n",
       "      <td>90</td>\n",
       "      <td>49850.0</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>7001</td>\n",
       "      <td>자동계량PC</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2.0</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:47</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:28:03</td>\n",
       "      <td>123</td>\n",
       "      <td>영진자원재생</td>\n",
       "      <td>폐기물</td>\n",
       "      <td>입고</td>\n",
       "      <td>7:28</td>\n",
       "      <td>7:47</td>\n",
       "      <td>11,370</td>\n",
       "      <td>12,180</td>\n",
       "      <td>810</td>\n",
       "      <td>49829.0</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>7001</td>\n",
       "      <td>자동계량PC</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3.0</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:53</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:44:05</td>\n",
       "      <td>1732</td>\n",
       "      <td>(주)원천환경</td>\n",
       "      <td>스티로폼</td>\n",
       "      <td>입고</td>\n",
       "      <td>7:53</td>\n",
       "      <td>7:44</td>\n",
       "      <td>5,020</td>\n",
       "      <td>5,120</td>\n",
       "      <td>100</td>\n",
       "      <td>31132.0</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>7001</td>\n",
       "      <td>자동계량PC</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4.0</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:55</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:48:31</td>\n",
       "      <td>8628</td>\n",
       "      <td>(주)향원실업</td>\n",
       "      <td>생활쓰레기</td>\n",
       "      <td>입고</td>\n",
       "      <td>7:55</td>\n",
       "      <td>7:48</td>\n",
       "      <td>7,580</td>\n",
       "      <td>12,260</td>\n",
       "      <td>4,680</td>\n",
       "      <td>12867.0</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>7001</td>\n",
       "      <td>자동계량PC</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5.0</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:59</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:53:30</td>\n",
       "      <td>1732</td>\n",
       "      <td>(주)원천환경</td>\n",
       "      <td>쇼파</td>\n",
       "      <td>입고</td>\n",
       "      <td>7:59</td>\n",
       "      <td>7:53</td>\n",
       "      <td>4,510</td>\n",
       "      <td>5,020</td>\n",
       "      <td>510</td>\n",
       "      <td>7864.0</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>7001</td>\n",
       "      <td>자동계량PC</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    전번        계량일자  계량시간        등록일자     등록시간     차량번호     거래처명     품목  구분  \\\n",
       "0  1.0  2020-01-02  7:41  2020-01-02  7:32:32  97고6890    (주)평촌   스티로폼  입고   \n",
       "1  2.0  2020-01-02  7:47  2020-01-02  7:28:03      123   영진자원재생    폐기물  입고   \n",
       "2  3.0  2020-01-02  7:53  2020-01-02  7:44:05     1732  (주)원천환경   스티로폼  입고   \n",
       "3  4.0  2020-01-02  7:55  2020-01-02  7:48:31     8628  (주)향원실업  생활쓰레기  입고   \n",
       "4  5.0  2020-01-02  7:59  2020-01-02  7:53:30     1732  (주)원천환경     쇼파  입고   \n",
       "\n",
       "   공차시간  상차시간     공중량     상중량    실중량     카드번호         1차전면명         1차상면명  \\\n",
       "0  7:41  7:32   5,830   5,920     90  49850.0  2.020010e+19  2.020010e+19   \n",
       "1  7:28  7:47  11,370  12,180    810  49829.0  2.020010e+19  2.020010e+19   \n",
       "2  7:53  7:44   5,020   5,120    100  31132.0  2.020010e+19  2.020010e+19   \n",
       "3  7:55  7:48   7,580  12,260  4,680  12867.0  2.020010e+19  2.020010e+19   \n",
       "4  7:59  7:53   4,510   5,020    510   7864.0  2.020010e+19  2.020010e+19   \n",
       "\n",
       "     지역     작업자  \n",
       "0  7001  자동계량PC  \n",
       "1  7001  자동계량PC  \n",
       "2  7001  자동계량PC  \n",
       "3  7001  자동계량PC  \n",
       "4  7001  자동계량PC  "
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 서부자원화시설_계근량(20) Read - Raw data\n",
    "\n",
    "data09=pd.read_csv('C:/Users/User/Desktop/공공빅데이터/화성시/Project1 폐기물/분석자료/서부자원화시설_계근량(20)(수정용).csv',\n",
    "                   encoding='utf-8')\n",
    "df09=pd.DataFrame(data09)\n",
    "\n",
    "## print(df09['구분'].isnull().sum()) == 863\n",
    "## print(len(df09)) == 38604\n",
    "\n",
    "df09=df09[df09['구분']=='입고']\n",
    "df07.to_csv('C:/Users/User/Desktop/공공빅데이터/화성시/Project1 폐기물/분석자료/서부자원화시설_계근량(20)(입고).csv', encoding='utf-8')\n",
    "df09.head(5)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "&nbsp;  \n",
    "### 2.2 &nbsp; 담당구역을 알 수 없는 거래처 추출  \n",
    "&nbsp;  \n",
    "- 2020년 폐기물 처리업체 list 와 미매칭되는 업체가 많음\n",
    "- 그런데 표기상의 문제(공백, (주)표기 등)로 다른 업체로 분류된 곳이 많음 -> 통일하여 데이터 정제 필요  \n",
    "&nbsp;  \n",
    "#### 1 &nbsp; 표준거래처 리스트 생성"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['㈜은호ENT', '㈜원천환경', '㈜평촌', '㈜화성', '향원실업㈜', '신양환경㈜', '㈜나눔환경', '㈜크린씨티화성', '부경크린㈜', '개미환경㈜', '㈜유나이트', '㈜바른환경']\n"
     ]
    }
   ],
   "source": [
    "# 거래처의 value를 모두 string으로 전환하여 list 재 생성 : 거래처 기준\n",
    "\n",
    "len(df02['업체명'])   # 12\n",
    "\n",
    "op_str = []\n",
    "\n",
    "for i in range(0,12) :\n",
    "    mid = []\n",
    "    mid = df02['업체명'][i].split(',')\n",
    "    \n",
    "    for item in mid :\n",
    "        item=item.strip()\n",
    "        op_str.append(item)\n",
    "        \n",
    "print(op_str)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 거래처 list를 기반으로 표준거래처 list 생성\n",
    "# len(org_list) == 12\n",
    "\n",
    "org_list = ['(주)은호ENT','(주)원천환경','(주)평촌','(주)화성','(주)향원실업','(주)신양환경','(주)나눔환경','(주)크린시티화성',\n",
    "           '(주)부경크린','(주)개미환경','(주)유나이트','(주)바른환경']"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "&nbsp;  \n",
    "#### 2 &nbsp; 표준거래처 사전 생성 및 적용"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- 동부적환장_계근량(19)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 거래처 list\n",
    "## print(set(df03['거래처']))\n",
    "\n",
    "op_list=['병점2동', '동탄5동', '양감면', '정남면', '매송면', '보건소', '남양읍', '월남참전전우회', '(주)신양환경', '엘 피 케이',\n",
    "         '동탄2동', '그린자원', '동부출장소', '팔탄', '자원화시설', '삼성환경개발', '삼흥개발', '지역개발사업소 산림녹지과',\n",
    "         '에코한마음', '동탄4동', '현화환경', '진안동', '(주)나눔환경', '동탄3동', '도로입양', '봉담읍', '삼희개발', '서신면',\n",
    "         '병점1동', '뉴그린', '동탄1동', '특수미래제단', '화산동', '자원화노면청소', '동탄출장소', '(주)향원실업', '신대한정유',\n",
    "         '반월동', '(주)평촌', '기배동', '(주)원천환경', '우정읍', '(주)크린시티화성', '마도', '오성개발', '주광건설', '(주)은호ENT',\n",
    "         '(주)화성', '대화안전관리', '미래재단', '제이스건설산업', '새한환경', '신대한정유산업', '(주)부경크린', '동탄6동', '자연수지']\n",
    "\n",
    "\n",
    "# 동부적환장_계근량(19) 표준거래처 사전\n",
    "\n",
    "org_dic = {'은호':'(주)은호ENT','원천환경':'(주)원천환경','평촌':'(주)평촌','향원실업':'(주)향원실업','신양':'(주)신양환경'\n",
    "           ,'나눔':'(주)나눔환경', '크린시티':'(주)크린시티화성','부경크린':'(주)부경크린'}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>1차 계량일</th>\n",
       "      <th>순번</th>\n",
       "      <th>2차계량일</th>\n",
       "      <th>1차시간</th>\n",
       "      <th>2차시간</th>\n",
       "      <th>차량번호숫자</th>\n",
       "      <th>거래처</th>\n",
       "      <th>품명</th>\n",
       "      <th>소속회사</th>\n",
       "      <th>공차중량</th>\n",
       "      <th>총중량</th>\n",
       "      <th>실중량</th>\n",
       "      <th>입/출고</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>1</td>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>9:23</td>\n",
       "      <td>9:25</td>\n",
       "      <td>8544</td>\n",
       "      <td>병점2동</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>화성시청</td>\n",
       "      <td>2210</td>\n",
       "      <td>2190</td>\n",
       "      <td>20</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>2</td>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>9:53</td>\n",
       "      <td>10:01</td>\n",
       "      <td>1119</td>\n",
       "      <td>(주)부경크린</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>반입업체</td>\n",
       "      <td>2390</td>\n",
       "      <td>2020</td>\n",
       "      <td>370</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>3</td>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>9:53</td>\n",
       "      <td>10:01</td>\n",
       "      <td>898</td>\n",
       "      <td>(주)은호ENT</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>반입업체</td>\n",
       "      <td>2720</td>\n",
       "      <td>2300</td>\n",
       "      <td>420</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>4</td>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>10:05</td>\n",
       "      <td>10:11</td>\n",
       "      <td>779</td>\n",
       "      <td>(주)크린시티화성</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>반입업체</td>\n",
       "      <td>2590</td>\n",
       "      <td>2280</td>\n",
       "      <td>310</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>5</td>\n",
       "      <td>2019-01-02</td>\n",
       "      <td>10:07</td>\n",
       "      <td>10:13</td>\n",
       "      <td>108</td>\n",
       "      <td>(주)부경크린</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>반입업체</td>\n",
       "      <td>2650</td>\n",
       "      <td>2170</td>\n",
       "      <td>480</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       1차 계량일  순번       2차계량일   1차시간   2차시간 차량번호숫자        거래처   품명  소속회사  \\\n",
       "0  2019-01-02   1  2019-01-02   9:23   9:25   8544       병점2동  폐합성  화성시청   \n",
       "1  2019-01-02   2  2019-01-02   9:53  10:01   1119    (주)부경크린  폐합성  반입업체   \n",
       "2  2019-01-02   3  2019-01-02   9:53  10:01    898   (주)은호ENT  폐합성  반입업체   \n",
       "3  2019-01-02   4  2019-01-02  10:05  10:11    779  (주)크린시티화성  폐합성  반입업체   \n",
       "4  2019-01-02   5  2019-01-02  10:07  10:13    108    (주)부경크린  폐합성  반입업체   \n",
       "\n",
       "   공차중량   총중량  실중량 입/출고  \n",
       "0  2210  2190   20   입고  \n",
       "1  2390  2020  370   입고  \n",
       "2  2720  2300  420   입고  \n",
       "3  2590  2280  310   입고  \n",
       "4  2650  2170  480   입고  "
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 거래처명 표준화\n",
    "\n",
    "for org_name in list(org_dic.keys()) :\n",
    "    df03=df03.replace(org_name,org_dic[org_name])\n",
    "df03.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['보건소', '월남참전전우회', '엘 피 케이', '그린자원', '동부출장소', '팔탄', '자원화시설', '삼성환경개발', '삼흥개발', '지역개발사업소 산림녹지과', '에코한마음', '현화환경', '도로입양', '삼희개발', '뉴그린', '특수미래제단', '자원화노면청소', '동탄출장소', '신대한정유', '마도', '오성개발', '주광건설', '대화안전관리', '미래재단', '제이스건설산업', '새한환경', '신대한정유산업', '자연수지']\n"
     ]
    }
   ],
   "source": [
    "# 동부적환장_계근량(19) 담당구역을 알 수 없는 거래처\n",
    "\n",
    "op_list_check = []\n",
    "\n",
    "for item in op_list :\n",
    "    if item not in (org_list + con_list) :\n",
    "        op_list_check.append(item)\n",
    "        \n",
    "print(op_list_check)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "&nbsp;  \n",
    "- 동부적환장_계근량(20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 거래처\n",
    "## print(set(df05['거래처']))\n",
    "\n",
    "op_list2=['병점2동', '동탄5동', '동탄청우실업', '동우상사', '양감면', '정남면', '동호산업', '남양읍', '(주)신양환경', '동탄2동',\n",
    "          '바른환경', '동부출장소', '팔탄', '우렁각시', '자원화시설', '더부름', '지역개발사업소 산림녹지과', '동탄4동', '(주)개미환경',\n",
    "          '(주)나눔환경', '진안동', '동탄3동', '봉담읍', '서신면', '병점1동', '동탄1동', '화산동', '동탄출장소', '(주)향원실업',\n",
    "          '반월동', '(주)평촌', '기배동', '(주)원천환경', '우정읍', '(주)크린시티화성', '마도', '(주)은호ENT', '(주)화성', '이크린',\n",
    "          '대화안전관리', '제일그린', '(주)부경크린', '동탄7동', '동탄6동', '송산']\n",
    "\n",
    "\n",
    "# 동부적환장_계근량(20) 표준거래처사전\n",
    "org_dic02 = {'은호':'(주)은호ENT','원천환경':'(주)원천환경','평촌':'(주)평촌', '화성':'(주)화성','향원':'(주)향원실업',\n",
    "             '향원실업':'(주)향원실업','신양':'(주)신양환경','나눔':'(주)나눔환경','크린시티':'(주)크린시티화성',\n",
    "             '부경크린':'(주)부경크린','개미환경':'(주)개미환경'}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>1차 계량일</th>\n",
       "      <th>순번</th>\n",
       "      <th>2차계량일</th>\n",
       "      <th>1차시간</th>\n",
       "      <th>2차시간</th>\n",
       "      <th>차량번호숫자</th>\n",
       "      <th>거래처</th>\n",
       "      <th>품명</th>\n",
       "      <th>소속회사</th>\n",
       "      <th>공차중량</th>\n",
       "      <th>총중량</th>\n",
       "      <th>실중량</th>\n",
       "      <th>입/출고</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2020-01-01</td>\n",
       "      <td>3</td>\n",
       "      <td>2020-01-01</td>\n",
       "      <td>15:38</td>\n",
       "      <td>15:38</td>\n",
       "      <td>279</td>\n",
       "      <td>동탄출장소</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>(주)화성시청</td>\n",
       "      <td>7,000</td>\n",
       "      <td>8,590</td>\n",
       "      <td>1,590</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>1</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>9:57</td>\n",
       "      <td>10:22</td>\n",
       "      <td>9184</td>\n",
       "      <td>반월동</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>(주)화성시청</td>\n",
       "      <td>2,480</td>\n",
       "      <td>2,180</td>\n",
       "      <td>300</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>2</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>10:04</td>\n",
       "      <td>10:06</td>\n",
       "      <td>8544</td>\n",
       "      <td>병점2동</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>(주)화성시청</td>\n",
       "      <td>2,210</td>\n",
       "      <td>2,190</td>\n",
       "      <td>20</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>4</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>10:10</td>\n",
       "      <td>10:15</td>\n",
       "      <td>9144</td>\n",
       "      <td>정남면</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>(주)화성시청</td>\n",
       "      <td>4,730</td>\n",
       "      <td>4,140</td>\n",
       "      <td>590</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>5</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>10:11</td>\n",
       "      <td>10:15</td>\n",
       "      <td>7934</td>\n",
       "      <td>기배동</td>\n",
       "      <td>폐합성</td>\n",
       "      <td>(주)화성시청</td>\n",
       "      <td>2,520</td>\n",
       "      <td>2,160</td>\n",
       "      <td>360</td>\n",
       "      <td>입고</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       1차 계량일  순번       2차계량일   1차시간   2차시간  차량번호숫자    거래처   품명     소속회사  \\\n",
       "2  2020-01-01   3  2020-01-01  15:38  15:38     279  동탄출장소  폐합성  (주)화성시청   \n",
       "3  2020-01-02   1  2020-01-02   9:57  10:22    9184    반월동  폐합성  (주)화성시청   \n",
       "4  2020-01-02   2  2020-01-02  10:04  10:06    8544   병점2동  폐합성  (주)화성시청   \n",
       "6  2020-01-02   4  2020-01-02  10:10  10:15    9144    정남면  폐합성  (주)화성시청   \n",
       "7  2020-01-02   5  2020-01-02  10:11  10:15    7934    기배동  폐합성  (주)화성시청   \n",
       "\n",
       "   공차중량    총중량    실중량  입/출고  \n",
       "2  7,000  8,590  1,590   입고  \n",
       "3  2,480  2,180    300   입고  \n",
       "4  2,210  2,190     20   입고  \n",
       "6  4,730  4,140    590   입고  \n",
       "7  2,520  2,160    360   입고  "
      ]
     },
     "execution_count": 41,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 거래처명 표준화\n",
    "\n",
    "for org_name02 in list(org_dic02.keys()) :\n",
    "    df05=df05.replace(org_name02,org_dic02[org_name02])\n",
    "df05.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['동탄청우실업', '동우상사', '동호산업', '바른환경', '동부출장소', '팔탄', '우렁각시', '자원화시설', '더부름', '지역개발사업소 산림녹지과', '동탄출장소', '마도', '이크린', '대화안전관리', '제일그린', '송산']\n"
     ]
    }
   ],
   "source": [
    "# 동부적환장_계근량(20) 담당구역을 알 수 없는 거래처\n",
    "\n",
    "op_list_check2 = []\n",
    "\n",
    "for item in op_list2 :\n",
    "    if item not in (org_list + con_list) :\n",
    "        op_list_check2.append(item)\n",
    "        \n",
    "print(op_list_check2)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "&nbsp;  \n",
    "- 서부자원화시설_계근량(19)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 거래처\n",
    "## print(set(df07['거래처']))\n",
    "\n",
    "op_list3=['영진자원재생', '동탄5동', '화성시청', '보건소', '특수임무유공자회', '(사)미래재단', '(주)씨에스그린', '대일개발',\n",
    "          '(주)두솔', '동탄4동', '삼성환경개발', '봉담읍', '서신면', '향남읍', '동탄1동', '화산동', '(주)피앤피시스템', '새한환경(주)',\n",
    "          '(주)평촌', '굴렁쇠협동조합', '도로관리과', '(주)청명(향남)', '(주)더위더스', '(주)화성', '화성그린환경센터', '대화안전관리',\n",
    "          '에코센터', '한국조명재활용공사', '전몰군경유족회', '두솔(향남신도시)', '제이스건설', '경기수질환경개발', '남양읍',\n",
    "          '정우리사이클링(주)', '동탄2동', '(주)자연수지', 'BSP경호단', '꿈에그린(주)', '가은이앤티', '자원화시설', '자원순환과',\n",
    "          '장안면', '(주)개미환경', '늘푸른산업', '팔탄면', '서부수도권자원순환센', '(주)엘피케이', '(주)향원실업', '(주)유나이트',\n",
    "          '이레자원', '청명2공장(향남신도시)', '청명제2공장(동탄2)', '(주)경기순환자원', '동탄6동', '국화도', '양감면', '(주)클린에코',\n",
    "          '현대연구소', '(주)신양환경', '동부출장소', '(주)신대한환경', '디에이치글로벌로지스', '새솔동', '클린에코(향남신도시)',\n",
    "          '기아자동차', '동탄8동', '삼희개발', '비봉면', '천일에너지', '에코한마음협동조합', '(주)원천환경', '우정읍', '세종환경(주)',\n",
    "          '청한공영(주)', '동탄7동', '에코리사이클링', '(주)피앤피', '송산면', '병점2동', '(주)신대한정유산업', '정남면', '고염제',\n",
    "          '매송면', '(주)청명', '(주)오성개발', '태주산업', '월남전참전회', '(주)나눔환경', '진안동', '동탄3동', '세종환경', '병점1동',\n",
    "          '마도면', '반월동', '기배동', '다누림사회', '(주)크린시티화성', '한국전지재활용협회', '청명제2공장', '(주)은호ENT',\n",
    "          '지채장회협회', '(주)부경크린', '전곡항', '광진데코', '자연수지']\n",
    "\n",
    "\n",
    "# 서부자원화시설_계근량(19) 표준거래처사전\n",
    "\n",
    "org_dic03={'신양환경':'(주)신양환경','(주)크린씨티화성':'(주)크린시티화성','(주)유나이트':'(주)유나이트','(주)나눔환경':'(주)나눔환경',\n",
    "          '(주)원천환경':'(주)원천환경','개미환경((주)':'(주)개미환경','(주)평촌':'(주)평촌','부경크린(주)':'(주)부경크린',\n",
    "          '(주)은호ENT':'(주)은호ENT','부경산업(주)':'(주)부경크린','향원실업':'(주)향원실업','(주)화성':'(주)화성',}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>계량일자</th>\n",
       "      <th>계량일시</th>\n",
       "      <th>등록일자</th>\n",
       "      <th>등록일시</th>\n",
       "      <th>순번</th>\n",
       "      <th>이력일자</th>\n",
       "      <th>이력시간</th>\n",
       "      <th>구분</th>\n",
       "      <th>입출</th>\n",
       "      <th>차량번호</th>\n",
       "      <th>...</th>\n",
       "      <th>Inout Flag</th>\n",
       "      <th>In Weight</th>\n",
       "      <th>End Flag</th>\n",
       "      <th>Prod Cost</th>\n",
       "      <th>Imagef No</th>\n",
       "      <th>Imager No</th>\n",
       "      <th>Imagef2 No</th>\n",
       "      <th>Imager2 No</th>\n",
       "      <th>Imageu No</th>\n",
       "      <th>Imageu2 No</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:24:36</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:24:36</td>\n",
       "      <td>1.0</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:24:42</td>\n",
       "      <td>등록</td>\n",
       "      <td>입고</td>\n",
       "      <td>3228</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>1480</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:42:15</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:28:25</td>\n",
       "      <td>4.0</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:42:15</td>\n",
       "      <td>등록</td>\n",
       "      <td>입고</td>\n",
       "      <td>416</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>180</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:50:02</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:30:38</td>\n",
       "      <td>5.0</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:50:02</td>\n",
       "      <td>등록</td>\n",
       "      <td>입고</td>\n",
       "      <td>2460</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>170</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:52:58</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:38:17</td>\n",
       "      <td>7.0</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:52:58</td>\n",
       "      <td>등록</td>\n",
       "      <td>입고</td>\n",
       "      <td>6371</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>220</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>8:02:36</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>7:55:46</td>\n",
       "      <td>8.0</td>\n",
       "      <td>2019-01-01</td>\n",
       "      <td>8:02:36</td>\n",
       "      <td>등록</td>\n",
       "      <td>입고</td>\n",
       "      <td>9011</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>1190</td>\n",
       "      <td>N</td>\n",
       "      <td>0</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "      <td>2.019010e+19</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 33 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         계량일자     계량일시        등록일자     등록일시   순번        이력일자     이력시간  구분  입출  \\\n",
       "1  2019-01-01  7:24:36  2019-01-01  7:24:36  1.0  2019-01-01  7:24:42  등록  입고   \n",
       "4  2019-01-01  7:42:15  2019-01-01  7:28:25  4.0  2019-01-01  7:42:15  등록  입고   \n",
       "5  2019-01-01  7:50:02  2019-01-01  7:30:38  5.0  2019-01-01  7:50:02  등록  입고   \n",
       "8  2019-01-01  7:52:58  2019-01-01  7:38:17  7.0  2019-01-01  7:52:58  등록  입고   \n",
       "9  2019-01-01  8:02:36  2019-01-01  7:55:46  8.0  2019-01-01  8:02:36  등록  입고   \n",
       "\n",
       "   차량번호  ... Inout Flag In Weight End Flag Prod Cost     Imagef No  \\\n",
       "1  3228  ...          2      1480        N         0  2.019010e+19   \n",
       "4   416  ...          2       180        N         0  2.019010e+19   \n",
       "5  2460  ...          2       170        N         0  2.019010e+19   \n",
       "8  6371  ...          2       220        N         0  2.019010e+19   \n",
       "9  9011  ...          2      1190        N         0  2.019010e+19   \n",
       "\n",
       "      Imager No    Imagef2 No    Imager2 No     Imageu No    Imageu2 No  \n",
       "1  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  \n",
       "4  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  \n",
       "5  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  \n",
       "8  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  \n",
       "9  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  2.019010e+19  \n",
       "\n",
       "[5 rows x 33 columns]"
      ]
     },
     "execution_count": 44,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 거래처명 표준화\n",
    "\n",
    "for org_name03 in list(org_dic03.keys()) :\n",
    "    df07=df07.replace(org_name03,org_dic03[org_name03])\n",
    "df07.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['영진자원재생', '화성시청', '보건소', '특수임무유공자회', '(사)미래재단', '(주)씨에스그린', '대일개발', '(주)두솔', '삼성환경개발', '(주)피앤피시스템', '새한환경(주)', '굴렁쇠협동조합', '도로관리과', '(주)청명(향남)', '(주)더위더스', '화성그린환경센터', '대화안전관리', '에코센터', '한국조명재활용공사', '전몰군경유족회', '두솔(향남신도시)', '제이스건설', '경기수질환경개발', '정우리사이클링(주)', '(주)자연수지', 'BSP경호단', '꿈에그린(주)', '가은이앤티', '자원화시설', '자원순환과', '늘푸른산업', '서부수도권자원순환센', '(주)엘피케이', '이레자원', '청명2공장(향남신도시)', '청명제2공장(동탄2)', '(주)경기순환자원', '국화도', '(주)클린에코', '현대연구소', '동부출장소', '(주)신대한환경', '디에이치글로벌로지스', '새솔동', '클린에코(향남신도시)', '기아자동차', '삼희개발', '천일에너지', '에코한마음협동조합', '세종환경(주)', '청한공영(주)', '에코리사이클링', '(주)피앤피', '(주)신대한정유산업', '고염제', '(주)청명', '(주)오성개발', '태주산업', '월남전참전회', '세종환경', '다누림사회', '한국전지재활용협회', '청명제2공장', '지채장회협회', '전곡항', '광진데코', '자연수지']\n"
     ]
    }
   ],
   "source": [
    "# 서부자원화시설_계근량(19)\n",
    "\n",
    "op_list_check3 = []\n",
    "\n",
    "for item in op_list3 :\n",
    "    if item not in (org_list + con_list) :\n",
    "        op_list_check3.append(item)\n",
    "        \n",
    "print(op_list_check3)\n",
    "\n",
    "op_check03=pd.DataFrame(op_list_check3)\n",
    "op_check03.to_csv('거래처3.csv', encoding='ANSI')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "&nbsp;  \n",
    "- 서부자원화시설_계근량(20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 서부자원화시설_계근량(20) 거래처\n",
    "## print(set(df09['거래처명']))\n",
    "\n",
    "op_list4=['동탄5동', '보건소', '(주)더블유알에스', '(주)씨에스그린', '(주)두솔', '동탄4동', '봉담읍', '서신면', '향남읍', '동탄1동',\n",
    "          '화산동', '동탄출장소', '(주)평촌', '굴렁쇠협동조합', '도로관리과', '(주)화성', '화성그린환경센터', '두솔(향남신도시)',\n",
    "          '남양읍', '정우리사이클링(주)', '동탄2동', '꿈에그린(주)', '산림녹지과', '자원화시설', '자원순환과', '장안면',\n",
    "          '경기환경에너지(주)', '(주)진흥중공업', '(주)개미환경', '팔탄면', '서부수도권자원순환센', '(주)향원실업', '(주)유나이트',\n",
    "          '이레자원', '(주)뉴그린', '청명2공장(향남신도시)', '알티코리아', '동탄6동', '현대환경(주)', '국화도', '양감면',\n",
    "          '(주)클린에코', '현대연구소', '(주)신양환경', '동부출장소', '(주)신대한환경', '새솔동', '유한회사 이크린',\n",
    "          '클린에코(향남신도시)', '비노텍(주)', '기아자동차', '동탄8동', '(주)컴윈', '비봉면', '(주)바른환경', '에코한마음협동조합',\n",
    "          '더브룸', '(주)원천환경', '우정읍', '동탄7동', '에코리사이클링', '송산면', '병점2동', '(주)신대한정유산업', '정남면',\n",
    "          '매송면', '(주)나눔환경', '진안동', '동탄3동', '병점1동', '마도면', '반월동', '기배동', '(주)크린시티화성',\n",
    "          '한국전지재활용협회', '청명제2공장', '(주)은호ENT', '우렁각시매직케어', '제일그린', '(주)부경크린', '영진자원재생']\n",
    "\n",
    "# 서부자원화시설_계근량(20) 표준거래처사전\n",
    "\n",
    "org_dic04={'(주)유나이트':'(주)유나이트','(주)평촌':'(주)평촌','(주)화성':'(주)화성','(주)나눔환경':'(주)나눔환경',\n",
    "           '부경크린(주)':'(주)부경크린','(주)크린씨티화성':'(주)크린시티화성','(주)은호ENT':'(주)은호ENT',\n",
    "           '(주)원천환경':'(주)원천환경','개미환경((주)':'(주)개미환경', '부경산업(주)':'(주)부경크린', '신양환경':'(주)신양환경',\n",
    "           '향원실업':'(주)향원실업',\n",
    "          '바른환경':'(주)바른환경'}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>전번</th>\n",
       "      <th>계량일자</th>\n",
       "      <th>계량시간</th>\n",
       "      <th>등록일자</th>\n",
       "      <th>등록시간</th>\n",
       "      <th>차량번호</th>\n",
       "      <th>거래처명</th>\n",
       "      <th>품목</th>\n",
       "      <th>구분</th>\n",
       "      <th>공차시간</th>\n",
       "      <th>상차시간</th>\n",
       "      <th>공중량</th>\n",
       "      <th>상중량</th>\n",
       "      <th>실중량</th>\n",
       "      <th>카드번호</th>\n",
       "      <th>1차전면명</th>\n",
       "      <th>1차상면명</th>\n",
       "      <th>지역</th>\n",
       "      <th>작업자</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1.0</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:41</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:32:32</td>\n",
       "      <td>97고6890</td>\n",
       "      <td>(주)평촌</td>\n",
       "      <td>스티로폼</td>\n",
       "      <td>입고</td>\n",
       "      <td>7:41</td>\n",
       "      <td>7:32</td>\n",
       "      <td>5,830</td>\n",
       "      <td>5,920</td>\n",
       "      <td>90</td>\n",
       "      <td>49850.0</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>7001</td>\n",
       "      <td>자동계량PC</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2.0</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:47</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:28:03</td>\n",
       "      <td>123</td>\n",
       "      <td>영진자원재생</td>\n",
       "      <td>폐기물</td>\n",
       "      <td>입고</td>\n",
       "      <td>7:28</td>\n",
       "      <td>7:47</td>\n",
       "      <td>11,370</td>\n",
       "      <td>12,180</td>\n",
       "      <td>810</td>\n",
       "      <td>49829.0</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>7001</td>\n",
       "      <td>자동계량PC</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3.0</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:53</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:44:05</td>\n",
       "      <td>1732</td>\n",
       "      <td>(주)원천환경</td>\n",
       "      <td>스티로폼</td>\n",
       "      <td>입고</td>\n",
       "      <td>7:53</td>\n",
       "      <td>7:44</td>\n",
       "      <td>5,020</td>\n",
       "      <td>5,120</td>\n",
       "      <td>100</td>\n",
       "      <td>31132.0</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>7001</td>\n",
       "      <td>자동계량PC</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4.0</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:55</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:48:31</td>\n",
       "      <td>8628</td>\n",
       "      <td>(주)향원실업</td>\n",
       "      <td>생활쓰레기</td>\n",
       "      <td>입고</td>\n",
       "      <td>7:55</td>\n",
       "      <td>7:48</td>\n",
       "      <td>7,580</td>\n",
       "      <td>12,260</td>\n",
       "      <td>4,680</td>\n",
       "      <td>12867.0</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>7001</td>\n",
       "      <td>자동계량PC</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5.0</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:59</td>\n",
       "      <td>2020-01-02</td>\n",
       "      <td>7:53:30</td>\n",
       "      <td>1732</td>\n",
       "      <td>(주)원천환경</td>\n",
       "      <td>쇼파</td>\n",
       "      <td>입고</td>\n",
       "      <td>7:59</td>\n",
       "      <td>7:53</td>\n",
       "      <td>4,510</td>\n",
       "      <td>5,020</td>\n",
       "      <td>510</td>\n",
       "      <td>7864.0</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>2.020010e+19</td>\n",
       "      <td>7001</td>\n",
       "      <td>자동계량PC</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    전번        계량일자  계량시간        등록일자     등록시간     차량번호     거래처명     품목  구분  \\\n",
       "0  1.0  2020-01-02  7:41  2020-01-02  7:32:32  97고6890    (주)평촌   스티로폼  입고   \n",
       "1  2.0  2020-01-02  7:47  2020-01-02  7:28:03      123   영진자원재생    폐기물  입고   \n",
       "2  3.0  2020-01-02  7:53  2020-01-02  7:44:05     1732  (주)원천환경   스티로폼  입고   \n",
       "3  4.0  2020-01-02  7:55  2020-01-02  7:48:31     8628  (주)향원실업  생활쓰레기  입고   \n",
       "4  5.0  2020-01-02  7:59  2020-01-02  7:53:30     1732  (주)원천환경     쇼파  입고   \n",
       "\n",
       "   공차시간  상차시간     공중량     상중량    실중량     카드번호         1차전면명         1차상면명  \\\n",
       "0  7:41  7:32   5,830   5,920     90  49850.0  2.020010e+19  2.020010e+19   \n",
       "1  7:28  7:47  11,370  12,180    810  49829.0  2.020010e+19  2.020010e+19   \n",
       "2  7:53  7:44   5,020   5,120    100  31132.0  2.020010e+19  2.020010e+19   \n",
       "3  7:55  7:48   7,580  12,260  4,680  12867.0  2.020010e+19  2.020010e+19   \n",
       "4  7:59  7:53   4,510   5,020    510   7864.0  2.020010e+19  2.020010e+19   \n",
       "\n",
       "     지역     작업자  \n",
       "0  7001  자동계량PC  \n",
       "1  7001  자동계량PC  \n",
       "2  7001  자동계량PC  \n",
       "3  7001  자동계량PC  \n",
       "4  7001  자동계량PC  "
      ]
     },
     "execution_count": 48,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 거래처명 표준화\n",
    "\n",
    "for org_name04 in list(org_dic04.keys()) :\n",
    "    df09=df09.replace(org_name04,org_dic04[org_name04])\n",
    "df09.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['보건소', '(주)더블유알에스', '(주)씨에스그린', '(주)두솔', '동탄출장소', '굴렁쇠협동조합', '도로관리과', '화성그린환경센터', '두솔(향남신도시)', '정우리사이클링(주)', '꿈에그린(주)', '산림녹지과', '자원화시설', '자원순환과', '경기환경에너지(주)', '(주)진흥중공업', '서부수도권자원순환센', '이레자원', '(주)뉴그린', '청명2공장(향남신도시)', '알티코리아', '현대환경(주)', '국화도', '(주)클린에코', '현대연구소', '동부출장소', '(주)신대한환경', '새솔동', '유한회사 이크린', '클린에코(향남신도시)', '비노텍(주)', '기아자동차', '(주)컴윈', '에코한마음협동조합', '더브룸', '에코리사이클링', '(주)신대한정유산업', '한국전지재활용협회', '청명제2공장', '우렁각시매직케어', '제일그린', '영진자원재생']\n"
     ]
    }
   ],
   "source": [
    "# 서부자원화시설_계근량(20)\n",
    "\n",
    "op_list_check4 = []\n",
    "\n",
    "for item in op_list4 :\n",
    "    if item not in (org_list + con_list) :\n",
    "        op_list_check4.append(item)\n",
    "        \n",
    "print(op_list_check4)\n",
    "\n",
    "op_check04=pd.DataFrame(op_list_check4)\n",
    "op_check04.to_csv('거래처4.csv', encoding='ANSI')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [],
   "source": [
    "df03.to_csv('동부적환장(19)_pre1.csv', encoding='ANSI',index=False)\n",
    "df05.to_csv('동부적환장(20)_pre1.csv', encoding='ANSI',index=False)\n",
    "df07.to_csv('서부자원화시설(19)_pre1.csv', encoding='ANSI',index=False)\n",
    "df09.to_csv('서부자원화시설(20)_pre1.csv', encoding='ANSI',index=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "&nbsp;  \n",
    "#### 2.3 위치를 알 수 없는 계근량  \n",
    "- 표기 상의 문제로 대부분의 업체가 다른 업체로 분류됨 -> 2.2에서 처리업체 정제 후 다시 수치확인"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.5025588536335721\n"
     ]
    }
   ],
   "source": [
    "# 동부(2019년)\n",
    "\n",
    "df03_columns=list(df03.columns.values)\n",
    "df04 = pd.DataFrame(columns=df03_columns)\n",
    "\n",
    "for op_name in op_list_check :\n",
    "    df04=pd.concat([df04,df03[df03['거래처']==op_name].copy()], ignore_index=True)\n",
    "    \n",
    "print(len(df04)/len(df03))   # 약 50%의 데이터에서 담당구역을 알 수 없음"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.4857452183327319\n"
     ]
    }
   ],
   "source": [
    "# 동부(2020년)\n",
    "\n",
    "df05_columns=list(df05.columns.values)\n",
    "df06 = pd.DataFrame(columns=df05_columns)\n",
    "\n",
    "for op_name in op_list_check2 :\n",
    "    df06=pd.concat([df06,df05[df05['거래처']==op_name].copy()], ignore_index=True)\n",
    "    \n",
    "print(len(df06)/len(df05))   # 약 48%의 데이터에서 담당구역을 알 수 없음"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.12506793317738238\n"
     ]
    }
   ],
   "source": [
    "# 서부(2019년)\n",
    "\n",
    "df07_columns=list(df07.columns.values)\n",
    "df08 = pd.DataFrame(columns=df07_columns)\n",
    "\n",
    "for op_name in op_list_check3 :\n",
    "    df08=pd.concat([df08,df07[df07['거래처']==op_name].copy()], ignore_index=True)\n",
    "    \n",
    "print(len(df08)/len(df07))   # 약 13%의 데이터에서 담당구역을 알 수 없음"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.06044229096782209\n"
     ]
    }
   ],
   "source": [
    "# 서부(2020년)\n",
    "\n",
    "df09_columns=list(df09.columns.values)\n",
    "df10 = pd.DataFrame(columns=df09_columns)\n",
    "\n",
    "for op_name in op_list_check4 :\n",
    "    df10=pd.concat([df10,df09[df09['거래처명']==op_name].copy()], ignore_index=True)\n",
    "    \n",
    "print(len(df10)/len(df09))   # 약 6%의 데이터에서 담당구역을 알 수 없음"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
